---
abstract: 'register documentation for routes'
author:
  - 'Aaron Cohen <aarondcohen@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker::CPANfile: 0.06
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Plugin-Documentation
no_index:
  directory:
    - t
    - inc
requires:
  Dancer: 0
  Dancer::Plugin: 0
  ExtUtils::MakeMaker: 0
  ExtUtils::MakeMaker::CPANfile: 0
  Moo: 0
  MooX::Types::MooseLike::Base: 0
  Scalar::Util: 0
  Set::Functional: 0
  Test::Most: 0
  namespace::clean: 0
resources:
  bugtracker: http://github.com/aarondcohen/perl-dancer-plugin-documentation/issues
  homepage: http://github.com/aarondcohen/perl-dancer-plugin-documentation
  repository: git://github.com/aarondcohen/perl-dancer-plugin-documentation.git
version: 0.02
